name: .NET Build

on:
  push:
    branches: [ "main", "NET-update" ]
  pull_request:
    branches: [ "main", "NET-update" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore "TeconMoon's WiiVC Injector.sln"

    - name: Build
      run: dotnet build "TeconMoon's WiiVC Injector.sln" --no-restore --configuration Release
